const allPalettes = [
	{
		id: 1,
		img: "sailing-boat.jpg",
		colors: [
			{ id: 1, hex: "#f2e5a1" },
			{ id: 2, hex: "#eebfa2" },
			{ id: 3, hex: "#b6ccbf" },
			{ id: 4, hex: "#202020" },
		],
		info: {
			title: "Sailing Boat, Evening Effect",
			author: "Claude Monet",
		},
		favorite: false,
		colorTags: ["yellow", "orange", "blue", "black"],
	},
	{
		id: 2,
		img: "menina.jpg",
		colors: [
			{ id: 1, hex: "#23356a" },
			{ id: 2, hex: "#688ac2" },
			{ id: 3, hex: "#fbf9e0" },
			{ id: 4, hex: "#d0b4c6" },
			{ id: 5, hex: "#9080c3" },
		],
		info: {
			title: "Menina",
			author: "Joaquín Sorolla",
		},
		favorite: false,
		colorTags: ["blue", "white", "purple"],
	},
	{
		id: 3,
		img: "sunflowers.jpg",
		colors: [
			{ id: 1, hex: "#ebe2b7" },
			{ id: 2, hex: "#b2c4b5" },
			{ id: 3, hex: "#d3a941" },
			{ id: 4, hex: "#5d2116" },
		],
		info: {
			title: "Sunflowers",
			author: "Vincent van Gogh",
		},
		favorite: false,
		colorTags: ["yellow", "blue", "red"],
	},
	{
		id: 4,
		img: "ophelia.jpg",
		colors: [
			{ id: 1, hex: "#593118" },
			{ id: 2, hex: "#ad9a86" },
			{ id: 3, hex: "#f0e1b5" },
			{ id: 4, hex: "#a8b98c" },
			{ id: 5, hex: "#456209" },
		],
		info: {
			title: "Ophelia",
			author: "J.E. Millais",
		},
		favorite: false,
		colorTags: ["beige", "yellow", "green", "brown"],
	},
	{
		id: 5,
		img: "frenzy.jpg",
		colors: [
			{ id: 1, hex: "#f1ebdb" },
			{ id: 2, hex: "#cfb987" },
			{ id: 3, hex: "#b98e3f" },
			{ id: 4, hex: "#131313" },
		],
		info: {
			title: "Frenzy",
			author: "Wladyslaw Podkowinski",
		},
		favorite: false,
		colorTags: ["black", "yellow", "beige"],
	},
	{
		id: 6,
		img: "girl-with-pearl.jpg",
		colors: [
			{ id: 1, hex: "#f9fbed" },
			{ id: 2, hex: "#ebd68d" },
			{ id: 3, hex: "#779dba" },
			{ id: 4, hex: "#a98853" },
			{ id: 5, hex: "#261e13" },
		],
		info: {
			title: "Girl with a Pearl Earing",
			author: "Johannes Vermeer",
		},
		favorite: false,
		colorTags: ["white", "blue", "yellow", "black", "brown"],
	},
	{
		id: 7,
		img: "flaming-june.jpg",
		colors: [
			{ id: 1, hex: "#e5cea8" },
			{ id: 2, hex: "#d18232" },
			{ id: 3, hex: "#724c1c" },
			{ id: 4, hex: "#3f1513" },
		],
		info: {
			title: "Flaming June",
			author: "Frederic Leighton",
		},
		favorite: false,
		colorTags: ["orange", "red", "brown", "beige"],
	},
	{
		id: 8,
		img: "girl-with-chrysanthemus.jpg",
		colors: [
			{ id: 1, hex: "#a78558" },
			{ id: 2, hex: "#f2f0f1" },
			{ id: 3, hex: "#a19ca0" },
			{ id: 4, hex: "#464650" },
		],
		info: {
			title: "Girl with Chrysathemus",
			author: "Olga Boznanska",
		},
		favorite: false,
		colorTags: ["grey", "brown", "white"],
	},
	{
		id: 9,
		img: "saint-jerome.jpg",
		colors: [
			{ id: 1, hex: "#e9ddcd" },
			{ id: 2, hex: "#aa9362" },
			{ id: 3, hex: "#892b19" },
			{ id: 4, hex: "#000000" },
		],
		info: {
			title: "Saint Jerome reading a letter",
			author: "Georges de La Tour",
		},
		favorite: false,
		colorTags: ["black", "beige", "red"],
	},
	{
		id: 10,
		img: "innocence.jpg",
		colors: [
			{ id: 1, hex: "#fce5c1" },
			{ id: 2, hex: "#d8c184" },
			{ id: 3, hex: "#94baa1" },
			{ id: 4, hex: "#1b6b81" },
		],
		info: {
			title: "Innocence",
			author: "Thomas Cooper Gotch",
		},
		favorite: false,
		colorTags: ["yellow", "beige", "blue"],
	},
	{
		id: 11,
		img: "storks.jpg",
		colors: [
			{ id: 1, hex: "#678f97" },
			{ id: 2, hex: "#e0cca3" },
			{ id: 3, hex: "#8c5614" },
			{ id: 4, hex: "#4f371e" },
			{ id: 5, hex: "#646e13" },
		],
		info: {
			title: "Storks",
			author: "Jozef Chelmonski",
		},
		favorite: false,
		colorTags: ["blue", "beige", "brown", "green"],
	},
	{
		id: 12,
		img: "mona-lisa.jpg",
		colors: [
			{ id: 1, hex: "#47573d" },
			{ id: 2, hex: "#a4a771" },
			{ id: 3, hex: "#efd685" },
			{ id: 4, hex: "#96652d" },
			{ id: 5, hex: "#462f28" },
		],
		info: {
			title: "Mona Lisa",
			author: "Leonardo da Vinci",
		},
		favorite: false,
		colorTags: ["yellow", "brown", "green"],
	},
	{
		id: 13,
		img: "starry-night.jpg",
		colors: [
			{ id: 1, hex: "#ddda8c" },
			{ id: 2, hex: "#cfa725" },
			{ id: 3, hex: "#82abd6" },
			{ id: 4, hex: "#1a2e93" },
			{ id: 5, hex: "#1d2238" },
		],
		info: {
			title: "Starry Night",
			author: "Vincent van Gogh",
		},
		favorite: false,
		colorTags: ["yellow", "blue"],
	},
	{
		id: 14,
		img: "grand-canal.jpg",
		colors: [
			{ id: 1, hex: "#d9eafe" },
			{ id: 2, hex: "#e5dafd" },
			{ id: 3, hex: "#d46ba3" },
			{ id: 4, hex: "#4731ba" },
		],
		info: {
			title: "The Grand Canal, Venice",
			author: "Claude Monet",
		},
		favorite: false,
		colorTags: ["blue", "purple", "pink"],
	},
	{
		id: 15,
		img: "mother.jpg",
		colors: [
			{ id: 1, hex: "#f5f1e3" },
			{ id: 2, hex: "#ebddc1" },
			{ id: 3, hex: "#cdbd98" },
			{ id: 4, hex: "#a09885" },
			{ id: 5, hex: "#07080c" },
		],
		info: {
			title: "Mother",
			author: "Joaquín Sorolla",
		},
		favorite: false,
		colorTags: ["beige", "grey", "black", "white"],
	},
	{
		id: 16,
		img: "roses-of-heliogabalus.jpg",
		colors: [
			{ id: 1, hex: "#c2effd" },
			{ id: 2, hex: "#f0eed9" },
			{ id: 3, hex: "#f8c7d5" },
			{ id: 4, hex: "#e57699" },
		],
		info: {
			title: "Roses of Heliogabalus",
			author: "Lawrence Alma-Tadema",
		},
		favorite: false,
		colorTags: ["pink", "blue", "beige", "white"],
	},
	{
		id: 17,
		img: "venus-of-urbino.jpg",
		colors: [
			{ id: 1, hex: "#ece9d6" },
			{ id: 2, hex: "#e4d1a2" },
			{ id: 3, hex: "#741013" },
			{ id: 4, hex: "#090806" },
		],
		info: {
			title: "Venus of Urbino",
			author: "Titian",
		},
		favorite: false,
		colorTags: ["beige", "red", "black"],
	},
	{
		id: 18,
		img: "almond-blossom.jpg",
		colors: [
			{ id: 1, hex: "#d5e7d6" },
			{ id: 2, hex: "#80acb2" },
			{ id: 3, hex: "#436e5a" },
		],
		info: {
			title: "Almond Blossom",
			author: "Vincent van Gogh",
		},
		favorite: false,
		colorTags: ["blue", "green"],
	},
	{
		id: 19,
		img: "kiss.jpg",
		colors: [
			{ id: 1, hex: "#d3c5a1" },
			{ id: 2, hex: "#dbc047" },
			{ id: 3, hex: "#645329" },
			{ id: 4, hex: "#2a2318" },
		],
		info: {
			title: "Kiss",
			author: "Gustav Klimt",
		},
		favorite: false,
		colorTags: ["yellow", "beige", "black", "brown"],
	},
	{
		id: 20,
		img: "profumo.jpg",
		colors: [
			{ id: 1, hex: "#87a5c7" },
			{ id: 2, hex: "#0851c1" },
			{ id: 3, hex: "#7d3476" },
			{ id: 4, hex: "#e1b83b" },
			{ id: 5, hex: "#86a134" },
		],
		info: {
			title: "Profumo",
			author: "Luigi Russolo",
		},
		favorite: false,
		colorTags: ["yellow", "purple", "green", "blue"],
	},
	{
		id: 21,
		img: "sami-on-skis.jpg",
		colors: [
			{ id: 1, hex: "#f9f1d5" },
			{ id: 2, hex: "#e6c996" },
			{ id: 3, hex: "#c6c487" },
			{ id: 4, hex: "#daa39f" },
			{ id: 5, hex: "#8a796d" },
		],
		info: {
			title: "Sami on skis in northern lights",
			author: "Frants Diderik Bøe",
		},
		favorite: false,
		colorTags: ["yellow", "green", "pink", "grey", "beige", "white"],
	},
	{
		id: 22,
		img: "summer-evening-at-skagen.jpg",
		colors: [
			{ id: 1, hex: "#ece6d6" },
			{ id: 2, hex: "#e1d298" },
			{ id: 3, hex: "#6e89c5" },
			{ id: 4, hex: "#432b17" },
		],
		info: {
			title: "Summer Evening at Skagen. The Artist's Wife and Dog by the Shore",
			author: "P.S. Krøyer",
		},
		favorite: false,
		colorTags: ["yellow", "blue", "brown"],
	},
	{
		id: 23,
		img: "landscape-with-violet-lights.jpg",
		colors: [
			{ id: 1, hex: "#f5d288" },
			{ id: 2, hex: "#a0557b" },
			{ id: 3, hex: "#5b3d32" },
		],
		info: {
			title: "Winter Landscape with Violet Lights",
			author: "Janos Tornyai",
		},
		favorite: false,
		colorTags: ["yellow", "purple", "brown"],
	},
	{
		id: 24,
		img: "ophelia-2.jpg",
		colors: [
			{ id: 1, hex: "#e8e4cb" },
			{ id: 2, hex: "#eacf81" },
			{ id: 3, hex: "#7c8c51" },
			{ id: 4, hex: "#3e4a30" },
		],
		info: {
			title: "Ophelia",
			author: "Pascal Adolphe Jean Dagnan-Bouveret",
		},
		favorite: false,
		colorTags: ["yellow", "green", "beige"],
	},
	{
		id: 25,
		img: "bay-of-marseille.jpg",
		colors: [
			{ id: 1, hex: "#83bed3" },
			{ id: 2, hex: "#4a71ac" },
			{ id: 3, hex: "#72ad72" },
			{ id: 5, hex: "#fddd6b" },
			{ id: 6, hex: "#d6814f" },
		],
		info: {
			title: "Bay of Marseille, view from L'Estaque",
			author: "Paul Cézanne",
		},
		favorite: false,
		colorTags: ["yellow", "green", "blue", "orange"],
	},
	{
		id: 26,
		img: "the-wailing-wall.jpg",
		colors: [
			{ id: 1, hex: "#fae7c3" },
			{ id: 2, hex: "#ecc27b" },
			{ id: 3, hex: "#bd8e37" },
			{ id: 4, hex: "#7c5415" },
		],
		info: {
			title: "The Wailing Wall",
			author: "J.L. Gerome",
		},
		favorite: false,
		colorTags: ["beige", "brown", "yellow"],
	},
	{
		id: 27,
		img: "moss-roses.jpg",
		colors: [
			{ id: 1, hex: "#dfc3c1" },
			{ id: 2, hex: "#bd888b" },
			{ id: 3, hex: "#5c6b51" },
			{ id: 4, hex: "#575755" },
		],
		info: {
			title: "Moss Roses in a Vase",
			author: "Édouard Manet",
		},
		favorite: false,
		colorTags: ["grey", "pink", "green"],
	},
	{
		id: 28,
		img: "moonlit-mountain-scenery.jpg",
		colors: [
			{ id: 1, hex: "#e3e5d1" },
			{ id: 2, hex: "#5cb2aa" },
			{ id: 3, hex: "#136870" },
			{ id: 4, hex: "#2a3844" },
		],
		info: {
			title: "Moonlit mountain scenery with people standing at a river",
			author: "Georg Emil Libert",
		},
		favorite: false,
		colorTags: ["blue", "white"],
	},
	{
		id: 29,
		img: "gypsy-woman.jpg",
		colors: [
			{ id: 1, hex: "#e3d8cf" },
			{ id: 2, hex: "#d9bb9d" },
			{ id: 3, hex: "#7187a9" },
			{ id: 4, hex: "#6c170c" },
		],
		info: {
			title: "Gypsy Woman",
			author: "Olga Boznanska",
		},
		favorite: false,
		colorTags: ["blue", "red", "beige"],
	},
	{
		id: 30,
		img: "calm-sea.jpg",
		colors: [
			{ id: 1, hex: "#eff5ee" },
			{ id: 2, hex: "#baf1e0" },
			{ id: 3, hex: "#7aabb0" },
			{ id: 4, hex: "#36558f" },
			{ id: 5, hex: "#132b57" },
		],
		info: {
			title: "Calm sea",
			author: "Ivan Aivazovsky",
		},
		favorite: false,
		colorTags: ["blue", "white"],
	},
];

export default allPalettes;
